### ISSUE TITLE
Arduino 1.8.12 IDE "call of overloaded, is ambiguous" Error

### ISSUE THREAD

**Issue by iw3row** [NicholasBerryman/GenericMotorDriver#4]
Compiling with latest IDE, only with library inclusion gives the following error:

D:\Documenti\Arduino\libraries\GenericMotorDriver\MotorController.cpp: In constructor 'MotorController::MotorController(unsigned int, unsigned int, unsigned int)':

D:\Documenti\Arduino\libraries\GenericMotorDriver\MotorController.cpp:14:68: error: call of overloaded 'MotorController(unsigned int&, unsigned int&, int)' is ambiguous

   : MotorController::MotorController(forwardPin,backwardsPin, false)

                                                                    ^

D:\Documenti\Arduino\libraries\GenericMotorDriver\MotorController.cpp:14:68: note: candidates are:

In file included from D:\Documenti\Arduino\libraries\GenericMotorDriver\MotorController.cpp:2:0:

D:\Documenti\Arduino\libraries\GenericMotorDriver\MotorController.h:15:5: note: MotorController::MotorController(unsigned int, unsigned int, unsigned int)

     MotorController(unsigned int forwardsPin, unsigned int backwardsPin, unsigned int enablePin);

     ^

D:\Documenti\Arduino\libraries\GenericMotorDriver\MotorController.cpp:4:1: note: MotorController::MotorController(unsigned int, unsigned int, bool)

 MotorController::MotorController(unsigned int forwardsPin, unsigned int backwardsPin, bool pin1IsDirection){

**Comment by NicholasBerryman** [comment]
It looks like there was an issue with implicit type conversions in the official Arduino compiler, this has been fixed in the latest release (which should propagate through to the package manager in a couple of hours). With the currrent world situation, I haven't been able to get to university and test the last few updates with any of my motor drivers, so I'm going to close this for now, but please let me know if there are any other problems.

**Comment by iw3row** [comment]
Thanks Nicholas, I forgot to mention that for this project I'm using the DUE board, not an AVR. 

UPDATE: Ok, got your update, it now compiles correctly! Thanks!
